### ISSUE TITLE
Issue deploying template via docker

### ISSUE THREAD

**Issue by milanpajovic** [cartesi/cli#130]
## 🙂 Expected behavior
Run docker image using templates for typesctipt application
What is expected to happen?

## 🫠 Actual behavior
    ExecaError: Command failed with exit code 1: docker container create --volume './.cartesi/image.tar:/tmp/input' 'cartesi/sdk:0.9.0' /usr/bin/env bash -c 
    'cat /tmp/input | crane export - - | bsdtar -cf /tmp/output --format=gnutar @/dev/stdin'

    Error response from daemon: create ./.cartesi/image.tar: "./.cartesi/image.tar" includes invalid characters for a local volume name, only 
    "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
`
`

## 🧪 Minimal test case

Please describe a minimal test case that demonstrates the bug.
If possible, this should be an automated test.

## 🌎 Environment
MAC 14 M1
What is the environment that the bug happens?
What is the Rollups version?
0.9.0
## ✔️ Possible solutions

(This section is optional.)
Any hint on how to solve the issue?
What parts of the code will be affected?

**Comment by tuler** [comment]
What is the output of `cartesi doctor`?

**Comment by milanpajovic** [comment]
> What is the output of `cartesi doctor`?
    Error: Unsupported Docker version. Minimum required version is 23.0.0. Installed version is 20.10.17.

Trying with new version

**Comment by milanpajovic** [comment]
> > What is the output of `cartesi doctor`?
> > Error: Unsupported Docker version. Minimum required version is 23.0.0. Installed version is 20.10.17.
> 
> Trying with new version

It helped, thank you
