### ISSUE TITLE
Programmatic access to image after build

### ISSUE THREAD

**Issue by guidanoli** [cartesi/cli#41]
## 📚 Context

I'd like to automate the process of building and pushing the node image, through a GitHub Actions workflow. However, in order to push an image to GHCR, I have to tag it, but the image that `cartesi deploy build` builds is not tagged, and its ID is not easily accessible. I could, of course, process the output of the command, or do some text-processing magic with the output of `docker images`, but...

## ✔️ Solution

A more consistent solution, in my view, would be to either...

- Allow the user to pass a tag to `cartesi deploy build`
- Write the image ID to a file, like Docker does with `--iidfile`, so that the user can run `docker tag` later or do whatever it wants with it, which could be exporting it to an archive file, etc.

**Comment by guidanoli** [comment]
I believe this has been addressed, right, @tuler?

**Comment by tuler** [comment]
Yes, using `cartesi deploy build --json`
