### ISSUE TITLE
Use GitHub Actions cache in builds

### ISSUE THREAD

**Issue by guidanoli** [cartesi/cli#68]
## 📚 Context

GitHub Actions provides [10 GB of cache space per repository](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy), which is great for us, developers, to save CI time :alarm_clock:.
Docker already has [great documentation](https://docs.docker.com/build/cache/backends/gha/) covering support to GitHub Actions cache backend.
Cartesi CLI, however, currently provides no way for us to cache Cartesi Machine or Cartesi Node image builds.

## ✔️ Solution

I see Cartesi CLI uses the `docker buildx build` command to build the [Cartesi Machine](https://github.com/cartesi/cli/blob/44c5cca6bea23c172802c0c03ddd8e494fbac38b/apps/cli/src/commands/build.ts#L72) and [Cartesi Node](https://github.com/cartesi/cli/blob/44c5cca6bea23c172802c0c03ddd8e494fbac38b/apps/cli/src/commands/deploy/build.ts#L39) images.
We need it to pass the following extra options:

- `--cache-from type=gha,scope=SCOPE`
- `--cache-to type=gha,mode=max,scope=SCOPE`

The `SCOPE` part should depend on the image being built, to avoid caching conflicts:

- Cartesi Machine: `cartesi-machine-image`
- Cartesi Node: `cartesi-node-image`

> [!NOTE]
> It seems that the `--builder` option doesn't have to be passed through the Docker CLI command, because we can set the [`BUILDX_BUILDER`](https://docs.docker.com/build/building/variables/#buildx_builder) environment variable instead, which creates less friction with Cartesi CLI.

The question now is: how will the Cartesi CLI know when to pass these extra options?
Well, it could detect the following environment variables set by the GitHub Actions runtime:

- `ACTIONS_CACHE_URL`
- `ACTIONS_RUNTIME_TOKEN`

But I haven't seen these mentioned in the GitHub API, so they could be experimental.
Instead, we could add `--cache-from` and `--cache-to` options to the following commands:

- `cartesi build`
- `cartesi deploy build`

**Comment by tuler** [comment]
The problem I see is there are a lot of options of docker buildx build, not only those related to cache.

One alternative that is already possible is to build the image using docker directly, and then using `—from-image`

**Comment by guidanoli** [comment]
> The problem I see is there are a lot of options of docker buildx build, not only those related to cache.

Fair enough. Well, we could support all of them by allowing the developer to pass any extra options, no?

> One alternative that is already possible is to build the image using docker directly, and then using —from-image

Yes, but even with the `--from-image` option, there is some work that could be cached.

**Comment by tuler** [comment]
> So, caching wouldn't make a difference, if the image is built before using docker directly?

You can use docker directly, with caching.
And then you `cartesi build --from-image` only to build the Cartesi machine.

**Comment by guidanoli** [comment]
Great! But what about `cartesi deploy build`?

**Comment by tuler** [comment]
> Great! But what about `cartesi deploy build`?

I don't think it makes sense for `cartesi deploy build`.
That command only brings together the Cartesi machine snapshot and the Cartesi Node.
I doesn't have a reason to take too much time.

**Comment by guidanoli** [comment]
> I doesn't have a reason to take too much time.

I guess you're right. I'm closing the issue.
